server:
  port: 8080

spring:
  application:
    name: order-api
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  datasource:
    url: jdbc:h2:mem:orderdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console

app:
  jwt:
    secret: v9y$B&E)H@MbQeThWmZq4t7w!z%C*F-JaNdRfUjXn2r5u8x/A?D(G+KbPeShVkYp
    expiration:
      minutes: 10
  cors:
    # allowed-origins: http://localhost:3000
    allowed-origins: http://localhost:5173

logging:
  level:
    org.springframework.security: DEBUG
